dist: bionic

language: node_js
node_js:
  - 14
git:
  autocrlf: false

os:
  - linux
  - osx
  - windows

#before_install:
#  - npm i -g npm@latest

script:
  - git clone -b master https://github.com/sCrypt-Inc/compiler_dist.git compiler
  - cd compiler && npm run dl
  - cd -
  - npm run testlint
  - npm run cov -- --ci=true
  # integration testing with boilerplate
  - npm link
  - git clone -b master https://github.com/scrypt-sv/boilerplate.git
  - cd boilerplate
  - npm install
  - npm link scryptlib # use this version
  #- npm ls scryptlib    # double check the latest version is used
  - npm test -- --ci=true
